In [2]:
import numpy as np
import time 
import sys

In [3]:
arr = np.array([1 , 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
size = 10_000_000
py_list = list(range(size))
start_time_1 = time.time()
sqaured = [x**2 for x in py_list]
end_time_1 = time.time()
print(f"the total time required in this python list is :---> {end_time_1-start_time_1}")

the total time required in this python list is :---> 0.4875795841217041


In [5]:
np_arr = np.array(py_list)
start_time_2 = time.time()
squared = np_arr ** 2
end_time_2 = time.time()
print(f"the total time required in this numpy array is :---> {end_time_2-start_time_2}")

the total time required in this numpy array is :---> 0.03193497657775879


In [6]:
print(f"the size of the python list is {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"the size of the numpy array is {np_arr.nbytes} bytes")

the size of the python list is 800000560000000 bytes
the size of the numpy array is 80000000 bytes


In [7]:
arr1 = np.array([[1,2,3] , [4,5,6] ,[7,8,9]])
print(arr1)
print(f"the shape of the numpy array is :-> {arr1.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the shape of the numpy array is :-> (3, 3)


In [8]:
arr2 = np.zeros((3,4))
print(arr2 , arr.dtype)

arr3 = np.ones((3,4))
arr4 = np.eye(4)
arr5 = np.arange(10,1,2)
print(arr3)
print(arr4)
print(arr5)

arr6 = np.empty((3,3))
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] int64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.89144859e-307 2.67018641e-306 1.42413555e-306]
 [1.78019082e-306 4.79243676e-322 0.00000000e+000]]


In [10]:
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
print(arr2.nbytes)
print(arr2.size)

arr_float = arr2.astype(np.float64)
print(arr_float , arr_float.dtype)


(3, 4)
float64
2
96
12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] float64


In [14]:
print(arr2)
reshaped = arr2.reshape((4,3))
print(f"the reshaped array is \n {reshaped}")

flatened = arr2.flatten()
print(f"the flattened array is :-> \n {flatened}")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the reshaped array is 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
the flattened array is :-> 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(arr)
idx = [1 , 2 , 3]
print(arr[idx])

print(arr[arr % 2 != 0])

[1 2 3 4 5]
[2 3 4]
[1 3 5]
